#!/usr/bin/env node
/**
 * gen-gtk.mjs - Reads vendor/gtk/gtkwindow.c and generates src/lib/gtkRules.generated.js
 * (the GTK4 resize-handle geometry constants).
 *
 * Design: narrow parser + assertions. Only the two `#define`s that size a CSD window's
 * input region are extracted; if upstream renames or re-types either one, this script
 * errors out instead of emitting a wrong value.
 *
 * Usage: node tools/gen-gtk.mjs [--check]
 *   --check: Verifies generated results match existing files (used by CI / check-style), exits with 1 if mismatch.
 */

import {readFileSync, writeFileSync, existsSync} from 'node:fs';
import {fileURLToPath} from 'node:url';
import path from 'node:path';

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const VENDOR = path.join(ROOT, 'vendor', 'gtk');
const OUT = path.join(ROOT, 'src', 'lib', 'gtkRules.generated.js');

const CHECK = process.argv.includes('--check');

function read(name) {
    const p = path.join(VENDOR, name);
    if (!existsSync(p))
        throw new Error(`[gen-gtk] Missing vendor file: ${name}`);
    return readFileSync(p, 'utf8');
}

/** Extract an integer object-like macro: `#define NAME 12` */
function parseDefine(cCode, name) {
    const re = new RegExp(`^#define\\s+${name}\\s+(\\d+)\\b`, 'm');
    const m = cCode.match(re);
    if (!m)
        throw new Error(`[gen-gtk] Assertion failed: #define ${name} not found in gtkwindow.c`);
    return parseInt(m[1], 10);
}

function main() {
    const cCode = read('gtkwindow.c');
    const handleSize = parseDefine(cCode, 'RESIZE_HANDLE_SIZE');
    const cornerSize = parseDefine(cCode, 'RESIZE_HANDLE_CORNER_SIZE');

    if (handleSize <= 0 || handleSize > 64)
        throw new Error(`[gen-gtk] Assertion failed: unexpected RESIZE_HANDLE_SIZE ${handleSize}`);
    if (cornerSize < handleSize)
        throw new Error(`[gen-gtk] Assertion failed: RESIZE_HANDLE_CORNER_SIZE ${cornerSize} < RESIZE_HANDLE_SIZE ${handleSize}`);

    const commit = read('COMMIT').trim();
    const code = `/**
 * GTK4 resize-handle geometry (**Generated file, do not edit directly**).
 *
 * Source: upstream GTK (vendor/gtk/COMMIT = ${commit})
 * Original: gtk/gtkwindow.c -- RESIZE_HANDLE_SIZE / RESIZE_HANDLE_CORNER_SIZE
 * Generated by: node tools/gen-gtk.mjs
 */

export const RESIZE_HANDLE_SIZE = ${handleSize};
export const RESIZE_HANDLE_CORNER_SIZE = ${cornerSize};
`;

    if (CHECK) {
        if (!existsSync(OUT)) {
            console.error(`[gen-gtk] --check failed: ${OUT} does not exist`);
            process.exit(1);
        }
        const existing = readFileSync(OUT, 'utf8');
        if (existing !== code) {
            console.error(`[gen-gtk] --check failed: ${OUT} does not match vendor/gtk/gtkwindow.c`);
            process.exit(1);
        }
        console.log(`[gen-gtk] --check passed: generated file matches vendor source code (commit ${commit.slice(0, 8)})`);
        return;
    }

    writeFileSync(OUT, code, 'utf8');
    console.log(`[gen-gtk] Successfully parsed and generated: ${path.relative(ROOT, OUT)}`);
}

main();
