#!/usr/bin/env node
/**
 * gen-clutter.mjs - Reads vendor/mutter/clutter-actor-box.c and generates
 * src/lib/clutterEffectPadding.generated.js (the Cogl/Clutter offscreen-effect
 * padding that sizes a shadow FBO).
 *
 * Design: narrow parser + assertions. Upstream's `_clutter_actor_box_enlarge_for_effects`
 * has one integer literal (`3`, the total padding per axis) and one float literal (`0.75`,
 * the rounding margin before `ceilf`). The `2px` top/left origin is NOT a literal: it is
 * what the rule produces on an integer-aligned box, so it is derived here by running the
 * same formula and asserting it comes out constant. A change to either literal upstream
 * moves the derived values and turns `--check` red.
 *
 * Usage: node tools/gen-clutter.mjs [--check]
 *   --check: Verifies generated results match the generated file (used by CI / check-style),
 *            exits with 1 if mismatch.
 */

import {readFileSync, writeFileSync, existsSync} from 'node:fs';
import {fileURLToPath} from 'node:url';
import path from 'node:path';

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const VENDOR = path.join(ROOT, 'vendor', 'mutter');
const OUT = path.join(ROOT, 'src', 'lib', 'clutterEffectPadding.generated.js');

const CHECK = process.argv.includes('--check');

function read(name) {
    const p = path.join(VENDOR, name);
    if (!existsSync(p))
        throw new Error(`[gen-clutter] Missing vendor file: ${name}`);
    return readFileSync(p, 'utf8');
}

/** Extract a balanced C function block, signature to closing brace. */
function extractFunction(source, signature) {
    const idx = source.indexOf(signature);
    if (idx < 0)
        throw new Error(`[gen-clutter] Assertion failed: cannot find function ${signature}`);
    const open = source.indexOf('{', idx);
    let depth = 0;
    for (let i = open; i < source.length; i++) {
        if (source[i] === '{') depth++;
        else if (source[i] === '}') {
            depth--;
            if (depth === 0)
                return source.slice(idx, i + 1);
        }
    }
    throw new Error(`[gen-clutter] Assertion failed: unclosed brace in ${signature}`);
}

/**
 * The upstream rule, transliterated so the origin can be derived rather than guessed.
 * `width` is `CLUTTER_NEARBYINT (box->x2 - box->x1)` in C.
 */
function enlargeBox(x1, x2, roundingPad, totalExtra) {
    const width = Math.round(x2 - x1);
    const newX2 = Math.ceil(x2 + roundingPad);
    const newX1 = newX2 - width - totalExtra;
    return {newX1, newX2};
}

function main() {
    const fn = extractFunction(read('clutter-actor-box.c'), '_clutter_actor_box_enlarge_for_effects');

    const roundingMatch = fn.match(/box->x2\s*=\s*ceilf\s*\(\s*box->x2\s*\+\s*(\d+(?:\.\d+)?)f\s*\)/);
    if (!roundingMatch)
        throw new Error('[gen-clutter] Assertion failed: `box->x2 = ceilf (box->x2 + 0.75f)` not found');
    const roundingPad = parseFloat(roundingMatch[1]);

    const extraMatch = fn.match(/box->x1\s*=\s*box->x2\s*-\s*width\s*-\s*(\d+)\s*;/);
    if (!extraMatch)
        throw new Error('[gen-clutter] Assertion failed: `box->x1 = box->x2 - width - 3` not found');
    const totalExtra = parseInt(extraMatch[1], 10);

    if (roundingPad <= 0 || roundingPad >= 1)
        throw new Error(`[gen-clutter] Assertion failed: unexpected rounding pad ${roundingPad}`);
    if (totalExtra <= 0 || totalExtra > 16)
        throw new Error(`[gen-clutter] Assertion failed: unexpected total extra ${totalExtra}`);

    // Derive the top-left origin across integer-aligned boxes: the split is an emergent
    // property of the formula, only constant when the box is integer-aligned.
    let origin = null;
    let farGrowth = null;
    for (let x1 = -8; x1 <= 8; x1++) {
        for (let width = 1; width <= 64; width++) {
            const {newX1, newX2} = enlargeBox(x1, x1 + width, roundingPad, totalExtra);
            const o = x1 - newX1;
            const g = newX2 - (x1 + width);
            if (origin === null) {
                origin = o;
                farGrowth = g;
            } else if (o !== origin || g !== farGrowth) {
                throw new Error(`[gen-clutter] Assertion failed: padding split not constant ` +
                    `(origin ${origin}/${o}, far ${farGrowth}/${g})`);
            }
        }
    }
    if (origin + farGrowth !== totalExtra)
        throw new Error(`[gen-clutter] Assertion failed: origin ${origin} + far ${farGrowth} != extra ${totalExtra}`);

    const commit = read('COMMIT').trim();
    const code = `/**
 * Cogl/Clutter offscreen-effect padding (**Generated file, do not edit directly**).
 *
 * Source: upstream Mutter/Clutter (vendor/mutter/COMMIT = ${commit})
 * Original: clutter/clutter/clutter-actor-box.c -- _clutter_actor_box_enlarge_for_effects
 * Generated by: node tools/gen-clutter.mjs
 *
 * Upstream rule (width = CLUTTER_NEARBYINT (box->x2 - box->x1)):
 *   box->x2 = ceilf (box->x2 + ${roundingPad}f);   // rounding margin before the ceil
 *   box->x1 = box->x2 - width - ${totalExtra};   // total padding per axis
 *
 * The ${totalExtra}px total is upstream's literal: it covers up to 1.75px on the
 * bottom/right while still leaving >0.75px on the top/left. The ${origin}px top/left
 * is NOT a literal - it is what that rule yields on an integer-aligned box:
 *   origin = box->x1 - (ceilf (box->x2 + ${roundingPad}f) - width - ${totalExtra}) = ${origin}
 * The 2/1 split only holds when the box is integer-aligned; the per-axis total stays
 * ${totalExtra}. See docs/architecture.md (Shadow baking).
 *
 * Note: EFFECT_ROUNDING_PAD (${roundingPad}f) is part of the upstream rule and is consumed
 * only at generation time (to derive EFFECT_PADDING_ORIGIN); it has no runtime consumer
 * — 规则的一部分，供推导使用；无运行时消费者。
 */

export const EFFECT_ROUNDING_PAD = ${roundingPad};  // upstream literal in ceilf (box->x2 + ${roundingPad}f)
export const EFFECT_PADDING_EXTRA = ${totalExtra};  // upstream literal: box->x2 - width - ${totalExtra}
export const EFFECT_PADDING_ORIGIN = ${origin};  // derived above, not an upstream literal
`;

    if (CHECK) {
        if (!existsSync(OUT)) {
            console.error(`[gen-clutter] --check failed: ${OUT} does not exist`);
            process.exit(1);
        }
        const existing = readFileSync(OUT, 'utf8');
        if (existing !== code) {
            console.error(`[gen-clutter] --check failed: ${OUT} does not match vendor/mutter/clutter-actor-box.c`);
            process.exit(1);
        }
        console.log(`[gen-clutter] --check passed: generated file matches vendor source (commit ${commit.slice(0, 8)})`);
        return;
    }

    writeFileSync(OUT, code, 'utf8');
    console.log(`[gen-clutter] Successfully parsed and generated: ${path.relative(ROOT, OUT)}`);
}

main();
